import StarBorderIcon from "@mui/icons-material/StarBorder";

const cardimg = [
  {
    id: 0,
    img: "https://modemus.ru/wp-content/uploads/2018/02/0cc3d3.jpg",
    title: "Furniture",
    dis: "chair",
    prize: "125$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 1,
    img: "https://5.imimg.com/data5/XM/HU/MY-3393888/designer-fancy-sofa-500x500.jpg",
    title: "Furniture",
    dis: "designer-fancy-sofa",
    prize: "555$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 2,
    img: "https://avatars.mds.yandex.net/i?id=ea40cc27eb342231b063526a6a26442b98328e25-8829620-images-thumbs&n=13",
    title: "Lighting",
    dis: "Awesome Lamp",
    prize: "59$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 3,
    img: "https://i.pinimg.com/originals/4b/bf/4c/4bbf4ca4b766b4658b5fde6913ebcb08.jpg",
    title: "Furniture",
    dis: "Sleeping bad",
    prize: "1189$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },

  {
    id: 4,
    img: "https://i.pinimg.com/originals/f9/73/c6/f973c6c3e5021bb1bab621e01b40bb9f.jpg",
    title: "Lighting",
    dis: "Awesome Lamp",
    prize: "59$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 5,
    img: "https://i.pinimg.com/736x/d1/d4/df/d1d4dfbf9f0477dbce88a63c30e12cc6--copper-lighting-copper-lamps.jpg",
    title: "Lighting",
    dis: "Awesome Lamp",
    prize: "259$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 6,
    img: "https://livinator.com/wp-content/uploads/2015/10/The-Sunflower-Bookchair-designed-By-He-Mu-and-Zhang-Qian.jpg",
    title: "Furniture",
    dis: "chair",
    prize: "125$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 7,
    img: "https://i.pinimg.com/originals/f5/80/66/f58066d5248fc01d3995eaf010ad9130.jpg",
    title: "Lighting",
    dis: "Awesome Lamp",
    prize: "59$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 8,
    img: "https://yandex-images.clstorage.net/XJh50n182/3b09214XA2E/Rpmw-gzWwtGDHkM430LWEF-SrVaepxjFYc7Dn58wMneAG5VVbr4xFkQaUoiSqCjU6FClgTevWPWXuRKsf1tZgRLK4-rcE1XFkhnTa96AlxeNVf9Wj2AMR6QIFkjOp-f2wZvPT3KjrMwZwJgBmHc7QuuFcJNw-hviDWCW8igBz8oK3TO3A0aNlsMFjvpZxpyUB5zvUQ8rzg5knBrDSPslIRCDyol-5-XI20dYCtcxNgggTLRVp_GZ7Eauj3lphM0NS9a4_IoEjRoDBYC72okUHwmU7lAMpgsPqtxbAoa_be1ZhgmKOWupwF5IUcsR_jMDLkB6nmq406OBowVzY8sPxE0Yun0CCUxUQs1I-9_JFhcIWmgZz-eKhaPTVAJJP6eq3olERr4g6YCfTZIEHnw8AWoN_NFr9tVsgmcNfCeKTwqMFf49ToxHGkOFAfHXxh2eD9nnmU2oRs0u2x_OAvKhKBuNTQ4_JqyG30XTDBn0d4joQT1ZZzcZaoMjgr3vhoyLT5x-P0iGSdWJSQX13E9W1AZVJ93H7M2Hq9OfS0Q7LWMXDgoN_OmliZJIUAEbPDbDLALwnyh02SwP7c15IIVFiEIe8_MCT0ccSkyN-5rHVxoJ02caResER2Hfn0HLsaes2Q0KSnojKEmRgJgIE_13CamAspflM1TigOpGuG3DRE1D2fGyQ4mNHUSMSb2ei5acwpjumAjjDUStmBvBTjTp6lzChUE3ZmjH0k1RA9u4tYppxLxd6HBR5UTsyjOphMCDwlB68wYHR9jKQMC9GsXc1IYTaNZBpAyEpB8QR8ixpmHTx8EI-6YoS1pJngobsbdLLcd71qP6UuAIq807qAoFC8jS8bWMBcKcAcwDMllF3xoAE-eRTyUChWAf183Lt6WsU4eISnRq5cXeTd8MnLk8CiHE-FPr-ZGrwCNF-m8Dw8zNUbpyy0YIFI6JSfLcAV4WBJItV49vRATr3RLCzk",
    title: "Lighting",
    dis: "Awesome Lamp",
    prize: "189$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 9,
    img: "https://i.pinimg.com/originals/0b/57/70/0b57703adcc3e614a04efc97e1d515be.jpg",
    title: "Furniture",
    dis: "chair",
    prize: "525$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 10,
    img: "https://i.pinimg.com/originals/b7/5b/94/b75b94cdd6eeddf189fb5e0cdf4f15f1.jpg",
    title: "Furniture",
    dis: "chair",
    prize: "725$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 11,
    img: "https://vostoklavka.ru/wa-data/public/shop/products/32/43/154332/images/1208764/1208764.970.jpg",
    title: "Decorestion",
    dis: "Wood Stand",
    prize: "125$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 12,
    img: "https://cdn.trendhunterstatic.com/thumbs/boll-lamp.jpeg?auto=webp",
    title: "Lighting",
    dis: "Awesome Lamp",
    prize: "359$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 13,
    img: "https://resources.burtonandburton.com/images/catalog/987433_l.jpg",
    title: "Furniture",
    dis: "Wood Baskets",
    prize: "485$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 45,
    img: "https://i.pinimg.com/736x/d7/c4/a8/d7c4a89380c3de009c2d1d42dd5f2ee0--tree-slices-wood-slices.jpg",
    title: "Decorestion",
    dis: "Decorestion",
    prize: "179$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 6,
    img: "https://cs5.livemaster.ru/storage/2a/ac/671d602e4cc99ebea499c154e6pm--kitchen-utensils-gift-set-for-the-kitchen-4-piece.jpg",
    title: "Kitchen",
    dis: "Decorestion",
    prize: "119$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
  {
    id: 7,
    img: "https://podarki-odessa.com/image/cache/catalog/originalnie-podarki/nabory-piknik/piknik-0503-028-a-750x750.jpg",
    title: "Furniture",
    dis: "Wood Baskets",
    prize: "300$",
    rating: [
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
      <StarBorderIcon />,
    ],
  },
];

export default cardimg;
